Repository Kernel360/F1-WashFit-FE, pull requests merged in 2024-02, with the labels that each got.

#148 페이지 기능: 로그인 성공시 redux에 id 저장
  package.json
  src/app/login/page.tsx
  src/providers/StoreProvider.tsx
  src/remote/api/requests/auth/auth.post.api.ts
  src/remote/api/types/auth.ts
  src/remote/api/types/common.ts
  src/remote/api/types/home.ts
  src/remote/queries/auth/useLogin.ts
  src/stores/slices/userSlice.ts
  src/stores/store.ts
  yarn.lock
Labels: ⚙ Setting, ✨ Feature

#151 페이지 기능: 회원가입 페이지 드롭다운 value 수정
  src/app/signup/page.tsx
  src/constants/dropdownMap.ts
Labels: ✨ Feature

#152 페이지 기능: 로그인 성공시 cookie에 token저장
  package.json
  src/app/layout.tsx
  src/providers/CookieProvider.tsx
  src/remote/queries/auth/useLogin.ts
  yarn.lock
Labels: ⚙ Setting, ✨ Feature

#153 페이지 기능: 제품 상세 페이지 쿼리 훅 제작 및 msw 추가
  src/app/car-details/page.tsx
  src/app/page.tsx
  src/app/product/[id]/page.tsx
  src/components/shared/carousel/Banner.scss
  src/components/shared/carousel/Banner.tsx
  src/components/shared/carousel/RecommendList.tsx
  src/components/shared/product-article/ProductArticle.tsx
  src/mocks/handlers.ts
  src/mocks/homeHandler/mocks.ts
  src/mocks/productHandler/index.ts
  src/mocks/productHandler/mocks.ts
  src/remote/api/requests/product/product.get.api.ts
  src/remote/api/types/home.ts
  src/remote/queries/product/useProductDetails.ts
Labels: ✨ Feature, ✅ Test

#157 페이지 기능: 마이페이지 문의하기 탭 및 링크 추가
  src/app/my-page/page.tsx
Labels: ✨ Feature, 🎨 Html&css

#158 페이지 기능: 마이페이지 로그인 유무에 따른 페이지 전환
  src/app/my-page/page.module.scss
  src/app/my-page/page.tsx
  src/components/shared/title/Title.tsx
Labels: ✨ Feature

#160 페이지 기능: 회원가입 페이지 약관동의 수정 및 회원가입 성공시 처리
  src/app/login/page.tsx
  src/app/signup/complete/page.tsx
  src/app/signup/page.tsx
  src/app/withdraw/page.module.scss
  src/app/withdraw/page.tsx
  src/components/shared/terms/Terms.module.scss
  src/components/shared/terms/Terms.tsx
  src/remote/queries/auth/useSignup.ts
  src/styles/button.ts
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#162 공통 컴포넌트 리팩토링: Header 뒤로가기 버튼
  src/app/car-wash-details/hydrated-page.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/app/signup/page.tsx
  src/components/shared/header/Header.tsx
  src/components/shared/header/headerItems/LeftIcon.tsx
  src/components/shared/header/types/headerType.ts
  src/components/shared/terms/Terms.tsx
Labels: ✨ Feature, 🔨 Refactor

#166 공통 컴포넌트: Confirmation 컴포넌트 제작
  src/app/change-password/complete/page.tsx
  src/app/find-id/complete/page.tsx
  src/app/my-page/page.tsx
  src/app/signup/complete/page.tsx
  src/components/shared/confirmation/Confirmation.scss
  src/components/shared/confirmation/Confirmation.tsx
  src/components/shared/header/Header.tsx
  src/constants/completeMessage.ts
  src/constants/requiredUser.ts
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#168 페이지 기능: 상세페이지 이미지 너비 수정
  src/app/product/[id]/page.tsx
Labels: 🎨 Html&css, 🐞 BugFix

#170 공통 컴포넌트: SEO
  src/components/shared/seo/SEO.tsx
Labels: ✨ Feature

#173 페이지 UI: 즐겨찾기 페이지
  src/app/favorite/page.module.scss
  src/app/favorite/page.tsx
  src/hooks/useScroll.ts
Labels: 🎨 Html&css

#174 페이지 기능: 로그인 페이지 카카오 UI 제작
  public/assets/kakao_login_medium_wide.png
  src/app/login/page.tsx
  src/components/home/kakao-login-button/KakaoLoginButton.module.scss
  src/components/home/kakao-login-button/KakaoLoginButton.tsx
  src/components/shared/kakao-script/KakaoLoginScript.tsx
  src/components/shared/map/KakaoMap.tsx
Labels: ✨ Feature, 🎨 Html&css

#176 페이지 기능: 로그아웃 쿼리 초기화
  src/app/my-page/page.tsx
Labels: ✨ Feature

#180 페이지 기능: 홈페이지 무한 스크롤 구현
  package.json
  src/app/page.tsx
  src/components/shared/product-article/ProductArticle.tsx
  src/remote/api/requests/home/home.get.api.ts
  src/remote/api/types/home.ts
  src/remote/queries/home/useProductList.ts
  yarn.lock
Labels: ✨ Feature

#183 페이지 기능: 아이디 찾기 기능
  src/app/find-id/complete/page.tsx
  src/app/find-id/page.tsx
  src/components/shared/kakao-script/KakaoLoginScript.tsx
  src/components/shared/modal/Modal.tsx
  src/contexts/ModalContext.tsx
  src/remote/api/requests/auth/auth.post.api.ts
  src/remote/queries/auth/useFindId.ts
Labels: ✨ Feature

#185 페이지 기능: 홈페이지 필터 기능 추가
  src/app/page.tsx
  src/components/home/filer-group/FilterGroup.tsx
  src/components/home/filer-group/types/filterGroup.type.ts
  src/remote/api/requests/home/home.get.api.ts
  src/remote/queries/home/useProductList.ts
Labels: ✨ Feature

#187 페이지 기능: 회원가입 페이지 및 아이디 찾기 페이지 토스트 적용
  package.json
  src/app/find-id/page.tsx
  src/app/layout.tsx
  src/providers/ToastProvider.tsx
  src/remote/queries/auth/useFindId.ts
  src/remote/queries/auth/useSignup.ts
  yarn.lock
Labels: ✨ Feature

#182 페이지 기능: 로그인 이후 토큰 인증에 따라 로그인 만료, 로그인 연장 처리
  src/app/layout.tsx
  src/app/my-page/page.tsx
  src/hooks/useIntervalRefreshToken.ts
  src/hooks/useLoggedOut.ts
  src/mocks/authHandler/index.ts
  src/mocks/authHandler/mocks.ts
  src/providers/RefreshTokenProvider.tsx
  src/remote/api/common.api.ts
  src/remote/api/requests/auth/auth.post.api.ts
  src/remote/api/requests/requests.api.ts
  src/remote/api/types/auth.ts
  src/remote/queries/auth/useRefreshToken.ts
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#189 페이지 기능: 홈페이지 스크롤 오류 수정
  public/assets/productList.webp
  src/components/shared/product-article/ProductArticle.module.scss
  src/components/shared/product-article/ProductArticle.tsx
Labels: 🐞 BugFix

#192 페이지 기능: 차량정보 등록 페이지 타입 변경
  src/components/additional-info/car-details/CarColorPicker.tsx
  src/components/additional-info/car-details/CarDetails.tsx
  src/remote/api/requests/additional-info/additional-info.get.api.ts
  src/remote/api/types/additional-info.ts
  src/remote/queries/additional-info/car-details/useCarColor.tsx
  src/remote/queries/additional-info/car-details/useCarDriving.tsx
  src/remote/queries/additional-info/car-details/useCarParking.tsx
  src/remote/queries/additional-info/car-details/useCarSegment.tsx
  src/remote/queries/additional-info/car-details/useCarType.tsx
  src/remote/queries/additional-info/car-wash-details/useCarWashCost.tsx
  src/remote/queries/additional-info/car-wash-details/useCarWashFrequency.tsx
  src/remote/queries/additional-info/car-wash-details/useCarWashInterest.tsx
Labels: 🐞 BugFix

#194 페이지 기능: 로그인 페이지 네이버 아이콘 추가
  public/assets/kakaoLoginButton.png
  public/assets/kakao_login_medium_wide.png
  public/assets/naverLoginButton.png
  src/app/login/page.tsx
  src/components/home/kakao-login-button/KakaoLoginButton.module.scss
  src/components/home/kakao-login-button/KakaoLoginButton.tsx
  src/components/home/naver-login-button/NaverLoginButton.tsx
  src/components/shared/kakao-script/KakaoScript.tsx
  src/components/shared/kakao-share-button/KakaoShareButton.tsx
Labels: ✨ Feature, 🎨 Html&css

#201 페이지 기능: 지도 페이지 마커 추가
  public/assets/marker.png
  src/app/map/page.tsx
  src/components/map/kakao-map/CurrentLocationButton.module.scss
  src/components/map/kakao-map/CurrentLocationButton.tsx
  src/components/map/kakao-map/KakaoMap.tsx
  src/components/map/markers/Markers.tsx
  src/remote/api/requests/map/map.get.api.ts
  src/remote/api/types/map.ts
  src/remote/queries/map/useMarkers.tsx
Labels: ✨ Feature

#203 환경설정: dockerfile 작성
  .github/workflows/cd-aws.yml
  .github/workflows/cd.yml
  .github/workflows/create_branch_for_issue.yml
  docker/Dockerfile
Labels: 🌏 Deploy

#207 페이지 기능: 즐겨찾기 페이지 api 연결
  src/app/favorite/page.module.scss
  src/app/favorite/page.tsx
  src/mocks/favoriteHandler/index.ts
  src/mocks/favoriteHandler/mock.ts
  src/mocks/handlers.ts
  src/remote/api/requests/favorite/favorite.get.api.ts
  src/remote/queries/favorite/useFavoriteList.ts
Labels: ✨ Feature

#208 환경 설정: ci test
  .github/workflows/ci.yml
Labels: ⚙ Setting, 🌏 Deploy

#209 환경설정: aws-ci 변경
  .github/workflows/cd-aws.yml
  Dockerfile
Labels: ⚙ Setting, 🌏 Deploy

#211 페이지 기능: 카카오 공유하기 url 수정
  .github/workflows/ci.yml
  src/components/shared/kakao-share-button/KakaoShareButton.tsx
Labels: 🐞 BugFix

#218 페이지 기능: 회원가입 페이지 중복 검사 기능 추가
  src/app/signup/page.test.tsx
  src/app/signup/page.tsx
  src/constants/validationMessage.ts
  src/remote/api/requests/auth/auth.get.api.ts
Labels: ✨ Feature

#220 페이지 기능: 채널 페이지 유튜브 api 연결
  package.json
  src/app/channel/page.module.scss
  src/app/channel/page.tsx
  src/components/shared/channel-article/ChannelArticle.module.scss
  src/components/shared/channel-article/ChannelArticle.stories.tsx
  src/components/shared/channel-article/ChannelArticle.tsx
  src/remote/api/requests/channel/channel.get.api.ts
  src/remote/api/types/channel.ts
  src/remote/queries/channel/useYoutubeList.ts
  yarn.lock
Labels: ⚙ Setting, ✨ Feature, 🎨 Html&css

#222 페이지 기능: 지도 페이지 마커 추가
  src/app/map/page.tsx
  src/components/map/car-wash-box/CarWashBox.module.scss
  src/components/map/car-wash-box/CarWashBox.tsx
  src/components/map/kakao-map/KakaoMap.tsx
  src/components/map/markers/Markers.tsx
Labels: ✨ Feature

#224 페이지 기능: 회원가입 약관
  src/components/shared/terms/Terms.module.scss
  src/components/shared/terms/Terms.tsx
  src/constants/terms/signupTerm.ts
Labels: 📃 Docs, 🔨 Refactor

#225 페이지 기능: 즐겨찾기 페이지 필터 기능 추가
  src/app/favorite/page.tsx
  src/hooks/withAuth.tsx
  src/remote/api/requests/favorite/favorite.get.api.ts
  src/remote/queries/favorite/useFavoriteList.ts
Labels: ✨ Feature

#227 페이지 기능: 차량 정보 입력 api 기능 추가
  src/app/car-details/hydrated-page.tsx
  src/app/car-wash-details/hydrated-page.tsx
  src/components/additional-info/car-details/CarColorPicker.tsx
  src/components/additional-info/car-details/CarDetails.tsx
  src/components/additional-info/car-details/color-picker/ColorPicker.stories.tsx
  src/components/additional-info/car-details/color-picker/ColorPicker.tsx
  src/remote/api/requests/additional-info/additional-info.post.api.ts
  src/remote/api/types/additional-info.ts
  src/remote/queries/additional-info/car-details/useRegisterCarDetails.tsx
  src/remote/queries/additional-info/car-wash-details/useRegisterCarWashDetails.tsx
Labels: ✨ Feature

#231 환경 설정: 쿠키 에러 수정
  src/app/my-page/page.tsx
  src/hooks/useLoggedOut.ts
  src/remote/api/common.api.ts
  src/remote/queries/auth/useLogin.ts
  src/types/cookies.type.ts
  src/utils/cookies.ts
Labels: 🐞 BugFix

#233 페이지 기능: 카카오 로그인 리다이렉트 기능 추가
  src/app/login/page.tsx
  src/app/oauth/kakao/page.tsx
Labels: ✨ Feature
