Repository Kernel360/F1-WashFit-FE, pull requests merged in 2024-03, with the labels that each got.

#238 페이지 기능: 마이페이지 api 기능 추가
  package.json
  src/app/(my-page)/my-page/page.tsx
  src/app/(my-page)/my-page/profile/page.tsx
  src/remote/api/requests/my-page/myPage.get.api.ts
  src/remote/api/requests/my-page/myPage.patch.api.ts
  src/remote/api/types/auth.ts
  src/remote/queries/my-page/useProfile.ts
  src/remote/queries/my-page/useUpdateProfile.ts
Labels: ✨ Feature

#240 페이지 오류: 회원가입 페이지 불필요한 api 요청 수정
  src/app/(auth)/signup/page.tsx
Labels: 🐞 BugFix

#244 페이지 기능: 유튜브 api 영상 목록에서 쇼츠 제외
  src/remote/api/requests/channel/channel.get.api.ts
Labels: ✨ Feature

#242 페이지 기능: 마이페이지 api 기능
  src/app/(auth)/signup/page.tsx
  src/app/(car-details)/car-details/hydrated-page.tsx
  src/app/(my-page)/my-page/car-details/page.tsx
  src/app/(my-page)/my-page/car-wash-details/page.tsx
  src/app/(my-page)/my-page/page.tsx
  src/app/(my-page)/my-page/profile/page.tsx
  src/constants/myPage.ts
  src/hooks/withRegisterCarDetails.tsx
  src/hooks/withRegisterCarWashDetails.tsx
  src/remote/api/requests/additional-info/additional-info.post.api.ts
  src/remote/api/types/additional-info.ts
  src/remote/api/types/my-page.ts
  src/utils/mappingCarDetails.ts
  src/utils/mappingCarWashDetails.ts
Labels: ✨ Feature

#246 페이지 기능: 추천 상품 리스트 api 적용
  public/assets/세정제.webp
  public/assets/코팅제.webp
  src/app/page.tsx
  src/components/shared/carousel/Banner.tsx
  src/components/shared/carousel/RecommendList.stories.tsx
  src/components/shared/carousel/RecommendList.tsx
  src/components/shared/carousel/RecommendListContainer.tsx
  src/mocks/homeHandler/mocks.ts
  src/remote/api/requests/home/home.get.api.ts
  src/remote/api/types/home.ts
Labels: ✨ Feature

#248 컴포넌트 기능: 리뷰 UI 제작
  src/app/product/[id]/page.tsx
Labels: 🎨 Html&css

#250 페이지 기능: 로그아웃 오류 수정
  src/app/(my-page)/my-page/page.tsx
  src/hooks/useLoggedOut.ts
Labels: 🐞 BugFix

#253 페이지 오류: 세차 정보 뒤로가기 기능 추가
  src/app/(car-details)/car-details/hydrated-page.tsx
  src/app/(car-details)/car-wash-details/hydrated-page.tsx
  src/app/(my-page)/my-page/page.tsx
  src/components/shared/header/types/headerType.ts
  src/remote/api/requests/auth/auth.post.api.ts
Labels: ✨ Feature, 🐞 BugFix

#254 페이지 기능: middleware 설정
  src/middleware.ts
Labels: ✨ Feature

#255 컴포넌트: FullPageLoader
  package.json
  src/app/(car-details)/car-details/hydrated-page.tsx
  src/app/(car-details)/car-wash-details/hydrated-page.tsx
  src/app/product/[id]/page.tsx
  src/components/shared/loader/FullPageLoader.module.scss
  src/components/shared/loader/FullPageLoader.tsx
  src/components/shared/loader/Loader.module.scss
  src/components/shared/loader/Loader.tsx
  src/lottie/loader.json
  tsconfig.json
  yarn.lock
Labels: ✨ Feature

#257 페이지 디자인: 홈페이지 디자인 수정
  src/app/(my-page)/my-page/page.tsx
  src/app/page.tsx
  src/components/shared/carousel/RecommendList.scss
  src/components/shared/carousel/RecommendList.tsx
  src/hooks/withAuth.tsx
Labels: 🎨 Html&css, 🐞 BugFix

#260 공통 컴포넌트: Confirmation 컴포넌트 수정
  src/app/(auth)/change-password/complete/page.tsx
  src/app/(auth)/find-id/complete/page.tsx
  src/app/(auth)/reset-password/complete/page.tsx
  src/components/shared/confirmation/Confirmation.scss
  src/components/shared/confirmation/Confirmation.tsx
Labels: 🎨 Html&css

#261 페이지 오류: 크로스 브라우징
  src/app/globals.css
  src/components/shared/header/headerItems/LeftIcon.tsx
Labels: 🎨 Html&css, 🐞 BugFix

#263 modal 및 Button 디자인 변경
  public/assets/logo.png
  public/assets/logo_text.png
  src/app/page.module.scss
  src/app/page.tsx
  src/components/icons/Logo.tsx
  src/components/shared/button/Button.tsx
  src/components/shared/carousel/Banner.scss
  src/components/shared/carousel/Banner.tsx
  src/components/shared/carousel/RecommendList.tsx
  src/components/shared/header/headerItems/LeftIcon.tsx
  src/components/shared/modal/Modal.module.scss
  src/components/shared/modal/Modal.stories.tsx
  src/components/shared/modal/Modal.tsx
  src/remote/api/requests/favorite/favorite.get.api.ts
  src/remote/queries/favorite/addFavoriteList.ts
  src/remote/queries/favorite/deleteFavoriteList.ts
Labels: 🎨 Html&css, 🔨 Refactor

#262 Update README.md
  README.md
Labels: 📃 Docs
